### ISSUE TITLE
complications updating

### ISSUE THREAD

**Issue by yhyates** [MahmoudAlsamman/Motivo-Apple-Watch-App#1]
the complications do not update every 5 mins in watch emulator of Xcode (watchos7+xcode12.3). does it work correctly on the real device? or how to perform normally on emulator? I am really interesting in how to refresh the complication without the app running on foreground or background. and the motivo is really cool.

**Comment by MahmoudAlsamman** [comment]
Hi, 
Thank you for your interest in my Repo 
I fixed it. 
please check it out:)
